version: "1.0"
title: "Tourniquet"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
  # Shared labels
  - id: 1
    label: "tourniquet_tourniquet"
  - id: 2
    label: "tourniquet_label"
  - id: 3
    label: "tourniquet_windlass"
  - id: 4
    label: "tourniquet_pen"
  - id: 5
    label: "hand (left)"
  - id: 6
    label: "hand (right)"
