version: "1"
title: "Tourniquet"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "background"
    full_str: "background"
  - id: 1
    label: "place-tourniquet"
    full_str: "Place tourniquet over affected extremity 2-3 inches above wound site."
  - id: 2
    label: "pull-tight"
    full_str: "Pull tourniquet tight."
  - id: 3
    label: "apply-strap-to-strap-body"
    full_str: "Apply strap to strap body."
  - id: 4
    label: "turn-windless"
    full_str: "Turn windless clock wise or counter clockwise until hemorrhage is controlled."
  - id: 5
    label: "lock-windless"
    full_str: "Lock windless into the windless keeper."
  - id: 6
    label: "pull-remaining-strap"
    full_str: "Pull remaining strap over the windless keeper."
  - id: 7
    label: "secure-strap"
    full_str: "Secure strap and windless keeper with keeper securing device."
  - id: 8
    label: "mark-time"
    full_str: "Mark time on securing device strap with permanent marker."
