model:
  _target_: src.models.unified_ho_module.UnifiedHOModule
  lr: 0.001
  weight_decay: 0
  data_type: video
  fcn:
    _target_: src.models.components.unified_fcn.UnifiedFCNModule
    net: resnext
    num_cpts: 21
    obj_classes: 9
    verb_classes: 12
  temporal:
    _target_: src.models.components.transformer.TemTRANSModule
    act_classes: 27
    hidden: 256
    dropout: 0.1
    depth: 6
model/params/total: 21369995
model/params/trainable: 21369995
model/params/non_trainable: 0
datamodule:
  _target_: src.datamodules.ros_datamodule.ROSDataModule
  pose_files:
    train_list: /data/dawei.du/datasets/ROS/Data/label_split/pose_train.txt
    val_list: /data/dawei.du/datasets/ROS/Data/label_split/pose_val.txt
    test_list: /data/dawei.du/datasets/ROS/Data/label_split/pose_val.txt
  action_files:
    train_list: /data/dawei.du/datasets/ROS/Data/label_split/new_action_train_32_more.txt
    val_list: /data/dawei.du/datasets/ROS/Data/label_split/new_action_val_32.txt
    test_list: /data/dawei.du/datasets/ROS/Data/label_split/brian_coffee_action_test.txt
  data_dir: /data/dawei.du/datasets/ROS/Data
  data_type: video
  batch_size: 64
  num_workers: 0
  pin_memory: false
  frames_per_segment: 32
trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  min_epochs: 1
  max_epochs: 100
  resume_from_checkpoint: null
seed: 25
callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val/acc
    mode: max
    save_top_k: 1
    save_last: false
    verbose: false
    dirpath: checkpoints/
    filename: epoch_{epoch:03d}
    auto_insert_metric_name: false
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val/acc
    mode: max
    patience: 100
    min_delta: 0
  model_summary:
    _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: -1
  rich_progress_bar:
    _target_: pytorch_lightning.callbacks.RichProgressBar
