//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class TaskItemMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/TaskItem";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Represents an item required for a task.
        // 
        //  Item name
        public string item_name;
        //  Item quantity
        public int quantity;

        public TaskItemMsg()
        {
            this.item_name = "";
            this.quantity = 0;
        }

        public TaskItemMsg(string item_name, int quantity)
        {
            this.item_name = item_name;
            this.quantity = quantity;
        }

        public static TaskItemMsg Deserialize(MessageDeserializer deserializer) => new TaskItemMsg(deserializer);

        private TaskItemMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.item_name);
            deserializer.Read(out this.quantity);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.item_name);
            serializer.Write(this.quantity);
        }

        public override string ToString()
        {
            return "TaskItemMsg: " +
            "\nitem_name: " + item_name.ToString() +
            "\nquantity: " + quantity.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
