_target_: src.datamodules.ros_datamodule.ROSDataModule

action_files:
  train_list: ${data_dir}/label_split/all_activities_action_train4.txt
  val_list: ${data_dir}/label_split/all_activities_action_val4.txt #all_activities_action_val hannah_action_test
  test_list: ${data_dir}/label_split/brian_coffee_action_test.txt

data_dir: ${data_dir} # data_dir is specified in test/train yaml file

batch_size: 64
num_workers: 0
pin_memory: False
frames_per_segment: 32
