version: "2.0"
title: "All Recipes"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  # - full_str: Complete sentence that fully represents the label.
  # - depends: List of ids that the item depends on
  # - repeat: Optional field that indicated that the item must be repeated X times
  - id: 0
    label: "background"
    full_str: "background"
  # Shared labels
  - id: 1
    label: "pour-water-kettle"
    full_str: "Pour the water from the liquid measuring cup into the electric kettle"
  - id: 2
    label: "turn-on-kettle"
    full_str: "Turn on the kettle"
  - id: 3
    label: "thermometer-turn-on"
    full_str: "Turn on the thermometer"
  - id: 4
    label: "thermometer-in-water"
    full_str: "Place the end of the thermometer into the water."
  - id: 5
    label: "place-tortilla"
    full_str: "Place tortilla on cutting board"
  - id: 6
    label: "slice-banana"
    full_str: "Slice banana"
  - id: 7
    label: "measure-water"
    full_str: "Measure water in the liquid measuring cup."
  # Labels that are the same across recipes but applied to different objects
  - id: 8 # same action, different ingredient
    label: "scoop-nutella"
    full_str: "Use the butter knife to scoop nutella from the jar"
  - id: 9
    label: "scoop-nutbutter"
    full_str: "Use the butter knife to scoop nut butter from the jar"
  - id: 10
    label: "scoop-jelly"
    full_str: "Use the butter knife to scoop jelly from the jar"
  - id: 11 # same action, different ingredient
    label: "spread-nutella-tortilla"
    full_str: "Spread nutella onto tortilla, leaving ½ inch uncovered at the edges"
  - id: 12
    label: "spread-nutbutter-tortilla"
    full_str: "Spread nut butter onto tortilla, leaving ½ inch uncovered at the edges"
  - id: 13
    label: "spread-jelly-tortilla"
    full_str: "Spread jelly onto tortilla, leaving ½ inch uncovered at the edges"
  - id: 14  # same action, different applications
    label: "dq-top-banana-slices"
    full_str: "Top with banana slices."
  - id: 15
    label: "oatmeal-top-banana-slices"
    full_str: "Top with banana slices."
  - id: 16 # same action, different applications
    label: "dq-sprinkle-cinnamon"
    full_str: "Sprinkle small amount of cinnamon onto tortilla"
  - id: 17 
    label: "oatmeal-sprinkle-cinnamon"
    full_str: "sprinkle with cinnamon"
  - id: 18 # same action, different applications
    label: "tea-add-honey"
    full_str: "Add honey to mug"
  - id: 19
    label: "oatmeal-drizzle-honey"
    full_str: "drizzle with honey"
  - id: 20 # same action, different ingredient
    label: "clean-knife"
    full_str: "Clean the knife by wiping with a paper towel."
  - id: 21 # same action, different applications
    label: "tea-stir"
    full_str: "Stir" 
  - id: 22
    label: "oatmeal-stir"
    full_str: "Stir"
  # Labels unique to coffee 
  - id: 23
    label: "place-dipper-on-mug"
    full_str: "Place the dripper on top of the mug"
  - id: 24
    label: "filter-fold-half"
    full_str: "Take the coffee filter and fold it in half to create a semi-circle"
  - id: 25
    label: "filter-fold-quarter"
    full_str: "Fold the filter in half again to create a quarter-circle"
  - id: 26
    label: "place-filter"
    full_str: "Place the folded filter into the dripper such that the the point of the quarter-circle rests in the center of the dripper"
  - id: 27
    label: "spread-filter"
    full_str: "Spread the filter open to create a cone inside the dripper"
  - id: 28
    label: "scale-press-btn"
    full_str: "Turn on/Zero the kitchen scale"
  - id: 29
    label: "place-bowl-on-scale"
    full_str: "Place a bowl on the scale"
  - id: 30
    label: "measure-coffee-beans"
    full_str: "Add coffee beans to the bowl until the scale reads 25 grams"
  - id: 31
    label: "pour-coffee-grinder"
    full_str: "Pour the measured coffee beans into the coffee grinder"
  - id: 32
    label: "grind-beans"
    full_str: "Grind the coffee beans by pressing and holding down on the black part of the lid"
  - id: 33
    label: "pour-beans-filter"
    full_str: "Transfer the grounds to the filter cone"
  - id: 34
    label: "pour-water-grounds-circular"
    full_str: "slowly pour the water over the grounds in a circular motion. do not overfill beyond the top of the paper filter"
  - id: 35
    label: "water-drain"
    full_str: "Allow the rest of the water in the dripper to drain"
  - id: 36
    label: "remove-dripper"
    full_str: "Remove the dripper from the cup"
  - id: 37
    label: "remove-grounds"
    full_str: "Remove the coffee grounds and paper filter from the dripper. "
  - id: 38
    label: "discard-grounds"
    full_str: "Discard the coffee grounds and paper filter"
  # Labels unique to dessert quesadilla
  - id: 39
    label: "fold-tortilla-half"
    full_str: "Fold tortilla in half into semi-circle"
  - id: 40
    label: "slice-tortilla-half"
    full_str: "Slice tortilla in half using butter knife to create two triangular wedges"
  - id: 41
    label: "place-tortilla-wedge"
    full_str: "Place tortilla wedge on the plate"
    repeat: 2
  # Labels unique to oatmeal
  - id: 42
    label: "pour-water-bowl"
    full_str: "Pour the water from the liquid measuring cup into the microwave safe bowl."
  - id: 43
    label: "measure-1-tbsp-oats"
    full_str: "Measure 1 Tablespoon of quick-cook oats and place in a microwave-safe bowl."
    repeat: 4
  - id: 44
    label: "add-raisins"
    full_str: "Add handful of raisins"
  - id: 45
    label: "microwave"
    full_str: "Microwave"
  # Labels unique to tea
  - id: 46
    label: "tea-bag-in-mug"
    full_str: "Place tea bag in mug"
  - id: 47
    label: "pour-water-mug"
    full_str: "Pour water from the electric kettle into the mug"
  - id: 48
    label: "remove-tea-bag"
    full_str: "Remove tea bag from mug"
  - id: 49
    label: "discard-tea-bag"
    full_str: "Discard tea bag"
  # Labels unique to pinwheel
  - id: 50
    label: "roll-tortilla"
    full_str: "Roll the tortilla from one end to the other into a log shape, about 1.5 inches thick. Roll it tight enough to prevent gaps, but not so tight that the filling leaks"
  - id: 51
    label: "insert-toothpick"
    full_str: "Insert a toothpick into the tortilla. The toothpick should be placed such that 5 total toothpicks can be placed about 1 inch apart."
    repeat: 5
  - id: 52
    label: "trim-tortilla"
    full_str: "Trim one end of the tortilla roll leaving ½” margin from the toothpick"
    repeat: 2
  - id: 53
    label: "discard-tortilla-ends"
    full_str: "Discard both ends of the tortilla"
  - id: 54
    label: "place-floss-between-toothpicks"
    full_str: "Slide floss under the tortilla, perpendicular to the length of the roll. Place the floss halfway between two toothpicks."
  # TODO: How to represent slicing the pinwheels so they can be repeated
  # with plating each pinwheel optionally after each slice
  - id: 55
    label: "cross-floss"
    full_str: "Cross the two ends of the floss over the top of the tortilla roll."
  - id: 56
    label: "floss-slice-tortilla"
    full_str: "Holding one end of the floss in each hand, pull the floss ends in opposite directions to slice."
    repeat: 4
  - id: 57
    label: "plate-pinwheels"
    full_str: "Place the pinwheels on a plate."
