version: "1"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  - id: 0
    label: "Background"
  - id: 1
    label: "Not started."
  - id: 2
    label: "Place tourniquet over affected extremity 2-3 inches above wound site (step 1)."
  - id: 3
    label: "In between step 1 and step 2."
  - id: 4
    label: "Pull tourniquet tight (step 2)."
  - id: 5
    label: "In between step 2 and step 3."
  - id: 6
    label: "Apply strap to strap body (step 3)."
  - id: 7
    label: "In between step 3 and step 4."
  - id: 8
    label: "Turn windless clock wise or counter clockwise until hemorrhage is controlled (step 4)."
  - id: 9
    label: "In between step 4 and step 5."
  - id: 10
    label: "Lock windless into the windless keeper (step 5)."
  - id: 11
    label: "In between step 5 and step 6."
  - id: 12
    label: "Pull remaining strap over the windless keeper (step 6)."
  - id: 13
    label: "In between step 6 and step 7."
  - id: 14
    label: "Secure strap and windless keeper with keeper securing device (step 7)."
  - id: 15
    label: "In between step 7 and step 8."
  - id: 16
    label: "Mark time on securing device strap with permanent marker (step 8)."
  - id: 17
    label: "Finished."
