version: "1.1"
# TODO: These activity ids should be updated to match those in 
# `all_recipe_labels.yaml` but they are being left for now until
# we can update the groundtruth labels as well
title: "Pour-over coffee"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  # - full_str: Complete sentence that fully represents the label.
  # - depends: List of ids that the item depends on
  # - repeat: Optional field that indicated that the item must be repeated X times
  - id: 0
    label: "background"
    full_str: "background"
  - id: 1
    label: "measure-12oz-water"
    full_str: "Measure 12 ounces of water in the liquid measuring cup"
    depends:
  - id: 2
    label: "pour-water-kettle"
    full_str: "Pour the water from the liquid measuring cup into the electric kettle"
    depends: [1]
  - id: 3
    label: "place-dipper-on-mug"
    full_str: "Place the dripper on top of the mug"
    depends:
  - id: 4
    label: "filter-fold-half"
    full_str: Take the coffee filter and fold it in half to create a semi-circle
    depends:
  - id: 5
    label: "filter-fold-quarter"
    full_str: "Fold the filter in half again to create a quarter-circle"
    depends: [4]
  - id: 6
    label: "place-filter"
    full_str: "Place the folded filter into the dripper such that the the point of the quarter-circle rests in the center of the dripper"
    depends: [5]
  - id: 7
    label: "spread-filter"
    full_str: "Spread the filter open to create a cone inside the dripper"
    depends: [6]
  - id: 8
    label: "scale-turn-on"
    full_str: "Turn on the kitchen scale"
    depends:
  - id: 9
    label: "place-bowl-on-scale"
    full_str: "Place a bowl on the scale"
    depends: [8]
  - id: 10
    label: "zero-scale"
    full_str: "Zero the scale"
    depends: [9]
  - id: 11
    label: "measure-coffee-beans"
    full_str: "Add coffee beans to the bowl until the scale reads 25 grams"
    depends: [10]
  - id: 12
    label: "pour-coffee-grinder"
    full_str: "Pour the measured coffee beans into the coffee grinder"
    depends: [11]
  - id: 13
    label: "grind-beans"
    full_str: "Grind the coffee beans by pressing and holding down on the black part of the lid"
    depends: [12]
  - id: 14
    label: "pour-beans-filter"
    #full_str: "Transfer the grounds to the filter cone"
    full_str: "pour the grounded coffee beans into the filter cone prepared in step 2"
    depends: [7, 13]
  - id: 15
    label: "thermometer-turn-on"
    full_str: "Turn on the thermometer"
    depends:
  - id: 16
    label: "thermometer-in-water"
    full_str: "Place the end of the thermometer into the water."
    depends: [2, 15, 24]
  - id: 17
    label: "check-thermometer"
    full_str: "Check the temperature displayed on the thermometer."
    depends: [16]
  - id: 18
    label: "pour-water-grounds-wet"
    #full_str: "Pour a small amount of water over the grounds in order to wet the grounds. Wait about 30 seconds."
    full_str: "Pour a small amount of water over the grounds in order to wet the grounds"
    depends: [14, 3, 17]
  - id: 19
    label: "pour-water-grounds-circular"
    full_str: "slowly pour the water over the grounds in a circular motion. do not overfill beyond the top of the paper filter"
    depends: [18]
  - id: 20
    label: "water-drain"
    full_str: "Allow the rest of the water in the dripper to drain"
    depends: [19]
  - id: 21
    label: "remove-dripper"
    full_str: "Remove the dripper from the cup"
    depends: [20]
  - id: 22
    label: "remove-grounds"
    full_str: "Remove the coffee grounds and paper filter from the dripper. "
    depends: [20]
  - id: 23
    label: "discard-grounds"
    full_str: "Discard the coffee grounds and paper filter"
    depends: [22]
  - id: 24
    label: "turn-on-kettle"
    full_str: "Turn on the kettle"
    depends: [2]
  - id: 25
    label: "done"
    full_str: "done"
    depends: [21, 23]
