version: "1"
# TODO: These activity ids should be updated to match those in 
# `all_recipe_labels.yaml` but they are being left for now until
# we can update the groundtruth labels as well
title: "Tea"
labels:
  # Item:
  # - id: Integer identification number of the label.
  # - label: Short human-readable semantic string to succinctly represent the
  #          label.
  # - full_str: Complete sentence that fully represents the label.
  # - depends: List of ids that the item depends on
  # - repeat: Optional field that indicated that the item must be repeated X times
  - id: 0
    label: "background"
  - id: 1
    label: "measure-12oz-water"
    full_str: "Measure 12 ounces of water in the liquid measuring cup"
    depends:
  - id: 2
    label: "pour-water-kettle"
    full_str: "Pour the water from the liquid measuring cup into the electric kettle"
    depends: [1]
  - id: 3
    label: "tea-bag-in-mug"
    full_str: "Place tea bag in mug"
    depends: 
  - id: 4
    label: "thermometer-turn-on"
    full_str: "Turn on the thermometer"
    depends: 
  - id: 5
    label: "thermometer-in-water"
    full_str: "Place the end of the thermometer into the water."
    depends: [2, 4]
  - id: 6
    label: "check-thermometer"
    full_str: "Check the temperature displayed on the thermometer."
    depends: [5]
  - id: 7
    label: "pour-water-mug"
    full_str: "Pour water from the electric kettle into the mug"
    depends: [6]
  - id: 8
    label: "steep"
    full_str: "Steep for 3 minutes"
    depends: [3, 7]
  - id: 9
    label: "remove-tea-bag"
    full_str: "Remove tea bag from mug"
    depends: [8]
  - id: 10
    label: "discard-tea-bag"
    full_str: "Discard tea bag"
    depends: [9]
  - id: 11
    label: "tea-add-honey"
    full_str: "Add honey to mug"
    depends:
  - id: 12
    label: "tea-stir"
    full_str: "Stir"
    depends: [7, 11]
  - id: 13
    label: "done"
    full_str: "done"
    depends: [10, 12]
