_BASE_: "/home/local/KHQ/hannah.defazio/angel_system/angel_system/berkeley/configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/data/ptg/medical/bbn/training/M2_Tourniquet/stage2/m2_with_lab_cleaned_data/resnet50/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 5
    SCORE_THRESH_TEST: 0.0001
    NAME: StandardROIHeads_PLUS_CONTACT
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("BBN_M2_train",)
  TEST: ("BBN_M2_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.5
  FILTER_EMPTY_ANNOTATIONS: True

OUTPUT_DIR: '/data/ptg/medical/bbn/annotations/M2_Tourniquet/results/'

SOLVER:
  TOTAL_IMAGE_NUMBER: 11949
  IMS_PER_BATCH: 21
  BASE_LR: 0.001
  STEPS: (34000, 41000)
# MAX_ITER: 64000 # 500 * 1 / 10 ~ 500 epochs
  CHECKPOINT_PERIOD: 1000
  EPOCH: 50

VISUALIZER:
  CAM: False

