//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class QueryImageSizeResponse : Message
    {
        public const string k_RosMessageName = "angel_msgs/QueryImageSize";
        public override string RosMessageName => k_RosMessageName;

        public short image_width;
        public short image_height;

        public QueryImageSizeResponse()
        {
            this.image_width = 0;
            this.image_height = 0;
        }

        public QueryImageSizeResponse(short image_width, short image_height)
        {
            this.image_width = image_width;
            this.image_height = image_height;
        }

        public static QueryImageSizeResponse Deserialize(MessageDeserializer deserializer) => new QueryImageSizeResponse(deserializer);

        private QueryImageSizeResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.image_width);
            deserializer.Read(out this.image_height);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.image_width);
            serializer.Write(this.image_height);
        }

        public override string ToString()
        {
            return "QueryImageSizeResponse: " +
            "\nimage_width: " + image_width.ToString() +
            "\nimage_height: " + image_height.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
