//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class QueryImageSizeRequest : Message
    {
        public const string k_RosMessageName = "angel_msgs/QueryImageSize";
        public override string RosMessageName => k_RosMessageName;

        //  Query the current image dimensions
        //  Note that image_width and image_height may be -1 if an image has not been
        //  received by the image_converter node yet

        public QueryImageSizeRequest()
        {
        }
        public static QueryImageSizeRequest Deserialize(MessageDeserializer deserializer) => new QueryImageSizeRequest(deserializer);

        private QueryImageSizeRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "QueryImageSizeRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
