//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class QueryAllObjects3dRequest : Message
    {
        public const string k_RosMessageName = "angel_msgs/QueryAllObjects3d";
        public override string RosMessageName => k_RosMessageName;

        //  Get all detected objects currently present in the world space.

        public QueryAllObjects3dRequest()
        {
        }
        public static QueryAllObjects3dRequest Deserialize(MessageDeserializer deserializer) => new QueryAllObjects3dRequest(deserializer);

        private QueryAllObjects3dRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "QueryAllObjects3dRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
