_BASE_: "/angel_workspace/angel_system/berkeley/configs/Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "/angel_workspace/model_files/ucb_coffee_preds_with_contact_r50.pth"
#  WEIGHTS: "/angel_workspace/model_files/berkeley_model_r50_with_contact_hl_hands.pth"
#  WEIGHTS: "/angel_workspace/model_files/berkeley_r50_activity_objs_only_hl_hands.pth"
#  WEIGHTS: "/Padlock_DT/training/berkeley/with_contact/include_empty_anns/resnet50_all_objects_only/model_final.pth"
  WEIGHTS: "/Padlock_DT/training/berkeley/with_contact/resnet50_all_objects_only_repeat_10/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 42
    SCORE_THRESH_TEST: 0.0001
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("COFFEE_train",)
  TEST: ("COFFEE_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
#SOLVER:
#  STEPS: (120000, 160000)
#  MAX_ITER: 180000  # 180000 * 16 / 100000 ~ 28.8 epochs
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.1

OUTPUT_DIR: '/Padlock_DT/'

SOLVER:
  TOTAL_IMAGE_NUMBER: 1040
  IMS_PER_BATCH: 1
# BASE_LR: 0.001
  BASE_LR: 0.0001
  STEPS: (34000, 41000)
  MAX_ITER: 64000 # 500 * 1 / 10 ~ 500 epochs
  CHECKPOINT_PERIOD: 1000
  EPOCH: 50

VISUALIZER:
  CAM: False


