//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class AnnotationEventMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/AnnotationEvent";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Message for annotation and error start/stop events.
        // 
        public Std.HeaderMsg header;
        //  Event description
        public string description;

        public AnnotationEventMsg()
        {
            this.header = new Std.HeaderMsg();
            this.description = "";
        }

        public AnnotationEventMsg(Std.HeaderMsg header, string description)
        {
            this.header = header;
            this.description = description;
        }

        public static AnnotationEventMsg Deserialize(MessageDeserializer deserializer) => new AnnotationEventMsg(deserializer);

        private AnnotationEventMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.description);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.description);
        }

        public override string ToString()
        {
            return "AnnotationEventMsg: " +
            "\nheader: " + header.ToString() +
            "\ndescription: " + description.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
