//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class AruiObject3dMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/AruiObject3d";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Object state update message to be sent to the AR-UI.
        // 
        //  This message is intended to represent a single object in 3D space
        // 
        //  Currently assumed a sub-component of the `AruiUpdate` message.
        // 
        //  Unique ID of this object.
        //  This value is likely a hash-like string, not something that has
        //  human-semantic meaning.
        //  This ID should be unique among all currently "active" 3D objects, e.g. no
        //  other 3D object that has not already been removed should share this ID.
        public string uid;
        //  Latest update time.
        public BuiltinInterfaces.TimeMsg stamp;
        //  Semantic label of this object.
        public string label;
        //  3D location of this object as a series of bounding-box coordinates.
        //  Following REP-103, the bbox "size" vector axis follow the right-hand rule.
        //  See "Axis Orientation" here: https://www.ros.org/reps/rep-0103.html#id21
        public VisionBoundingBox3dMsg bbox;

        public AruiObject3dMsg()
        {
            this.uid = "";
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.label = "";
            this.bbox = new VisionBoundingBox3dMsg();
        }

        public AruiObject3dMsg(string uid, BuiltinInterfaces.TimeMsg stamp, string label, VisionBoundingBox3dMsg bbox)
        {
            this.uid = uid;
            this.stamp = stamp;
            this.label = label;
            this.bbox = bbox;
        }

        public static AruiObject3dMsg Deserialize(MessageDeserializer deserializer) => new AruiObject3dMsg(deserializer);

        private AruiObject3dMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.uid);
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.label);
            this.bbox = VisionBoundingBox3dMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.uid);
            serializer.Write(this.stamp);
            serializer.Write(this.label);
            serializer.Write(this.bbox);
        }

        public override string ToString()
        {
            return "AruiObject3dMsg: " +
            "\nuid: " + uid.ToString() +
            "\nstamp: " + stamp.ToString() +
            "\nlabel: " + label.ToString() +
            "\nbbox: " + bbox.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
