//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class AruiUserNotificationMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/AruiUserNotification";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Message communicating a single notification for the ARUI to present to the
        //  user.
        // 
        //  A notification may be handed in certain ways based on the combination of both
        //  the notification context and category.
        // 
        // ##############################################################################
        //  Notification category constants.
        //  Basically the priority in which the notification should be treated.
        //  https://www.mysafetysign.com/danger-caution-warning-safety-sign-headers
        public const byte N_CAT_DANGER = 0;
        public const byte N_CAT_WARNING = 1;
        public const byte N_CAT_CAUTION = 2;
        public const byte N_CAT_NOTICE = 3;
        //  Notification category. See constants above.
        public byte category;
        // ##############################################################################
        //  Notification context constants.
        //  Different notifications can have different contexts from which they are
        //  emitted that the UI will want to handle differently.
        //  There is some error the user performed in the task
        public const byte N_CONTEXT_TASK_ERROR = 0;
        //  There is something in the environment this notification pertains to. Likely spatial in nature.
        public const byte N_CONTEXT_ENV_ATTENTION = 1;
        //  This notification is in regards to the user modeling (e.g. user frustration).
        public const byte N_CONTEXT_USER_MODELING = 2;
        //  Notification context. See constants above.
        public byte context;
        // ##############################################################################
        //  Textual details to go with this notification.
        //  A short message about this notification.
        public string title;
        //  Potentially longer description of this notification.
        public string description;
        // ##############################################################################
        //  Spatial associations for this notification.
        //  0 or more  3D objects this notification is associated with, by UID.
        public string[] associated_object_uids;
        //  0 or more spatial polygons this notification is associated with.
        //  Expected to mark surfaces.
        public Geometry.PolygonMsg[] associated_polys;

        public AruiUserNotificationMsg()
        {
            this.category = 0;
            this.context = 0;
            this.title = "";
            this.description = "";
            this.associated_object_uids = new string[0];
            this.associated_polys = new Geometry.PolygonMsg[0];
        }

        public AruiUserNotificationMsg(byte category, byte context, string title, string description, string[] associated_object_uids, Geometry.PolygonMsg[] associated_polys)
        {
            this.category = category;
            this.context = context;
            this.title = title;
            this.description = description;
            this.associated_object_uids = associated_object_uids;
            this.associated_polys = associated_polys;
        }

        public static AruiUserNotificationMsg Deserialize(MessageDeserializer deserializer) => new AruiUserNotificationMsg(deserializer);

        private AruiUserNotificationMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.category);
            deserializer.Read(out this.context);
            deserializer.Read(out this.title);
            deserializer.Read(out this.description);
            deserializer.Read(out this.associated_object_uids, deserializer.ReadLength());
            deserializer.Read(out this.associated_polys, Geometry.PolygonMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.category);
            serializer.Write(this.context);
            serializer.Write(this.title);
            serializer.Write(this.description);
            serializer.WriteLength(this.associated_object_uids);
            serializer.Write(this.associated_object_uids);
            serializer.WriteLength(this.associated_polys);
            serializer.Write(this.associated_polys);
        }

        public override string ToString()
        {
            return "AruiUserNotificationMsg: " +
            "\ncategory: " + category.ToString() +
            "\ncontext: " + context.ToString() +
            "\ntitle: " + title.ToString() +
            "\ndescription: " + description.ToString() +
            "\nassociated_object_uids: " + System.String.Join(", ", associated_object_uids.ToList()) +
            "\nassociated_polys: " + System.String.Join(", ", associated_polys.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
