//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class InterpretedAudioUserIntentMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/InterpretedAudioUserIntent";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Message communicating an interpreted User Intent from an audio-based user
        //  utterance.
        // 
        //  numerical identifier of this utterance intent deduction
        public ulong id;
        //  Speech-to-text of the user utterance we have interpreted
        public string utterance_text;
        //  Canonical user intent that has been interpreted. "Canonical" in this context
        //  is to mean that this string may be used as an identifier of this type of
        //  user intent.
        public string user_intent;
        //  Confidence we think this intent was targetted at the ANGEL system.
        //  Should be in the range [0,1] where 1.0 means absolute confidence the target is the ANGEL
        //  system and 0.0 is absolute confidence the target IS NOT the ANGEL system.
        public double confidence;

        public InterpretedAudioUserIntentMsg()
        {
            this.id = 0;
            this.utterance_text = "";
            this.user_intent = "";
            this.confidence = 0.0;
        }

        public InterpretedAudioUserIntentMsg(ulong id, string utterance_text, string user_intent, double confidence)
        {
            this.id = id;
            this.utterance_text = utterance_text;
            this.user_intent = user_intent;
            this.confidence = confidence;
        }

        public static InterpretedAudioUserIntentMsg Deserialize(MessageDeserializer deserializer) => new InterpretedAudioUserIntentMsg(deserializer);

        private InterpretedAudioUserIntentMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.utterance_text);
            deserializer.Read(out this.user_intent);
            deserializer.Read(out this.confidence);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.utterance_text);
            serializer.Write(this.user_intent);
            serializer.Write(this.confidence);
        }

        public override string ToString()
        {
            return "InterpretedAudioUserIntentMsg: " +
            "\nid: " + id.ToString() +
            "\nutterance_text: " + utterance_text.ToString() +
            "\nuser_intent: " + user_intent.ToString() +
            "\nconfidence: " + confidence.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
