//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class IntentDetectionMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/IntentDetection";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  An intent detection on an utterance.
        // 
        //  Class labels and prediction confidences.
        //  conf_vec[i] corresponds to the prediction confidence for the class at
        //  label_vec[i].
        public string[] label_vec;
        public float[] conf_vec;

        public IntentDetectionMsg()
        {
            this.label_vec = new string[0];
            this.conf_vec = new float[0];
        }

        public IntentDetectionMsg(string[] label_vec, float[] conf_vec)
        {
            this.label_vec = label_vec;
            this.conf_vec = conf_vec;
        }

        public static IntentDetectionMsg Deserialize(MessageDeserializer deserializer) => new IntentDetectionMsg(deserializer);

        private IntentDetectionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.label_vec, deserializer.ReadLength());
            deserializer.Read(out this.conf_vec, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.label_vec);
            serializer.Write(this.label_vec);
            serializer.WriteLength(this.conf_vec);
            serializer.Write(this.conf_vec);
        }

        public override string ToString()
        {
            return "IntentDetectionMsg: " +
            "\nlabel_vec: " + System.String.Join(", ", label_vec.ToList()) +
            "\nconf_vec: " + System.String.Join(", ", conf_vec.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
