//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class JointKeypointsMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/JointKeypoints";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Message that contains a snapshot of the patient joint poses
        // 
        //  Header frame_id should indicate the source these detections were predicted
        //  over.
        public Std.HeaderMsg header;
        //  Timestamp of the source image these predictions pertain to.
        public BuiltinInterfaces.TimeMsg source_stamp;
        //  List of joints
        public double[] keypoints;

        public JointKeypointsMsg()
        {
            this.header = new Std.HeaderMsg();
            this.source_stamp = new BuiltinInterfaces.TimeMsg();
            this.keypoints = new double[0];
        }

        public JointKeypointsMsg(Std.HeaderMsg header, BuiltinInterfaces.TimeMsg source_stamp, double[] keypoints)
        {
            this.header = header;
            this.source_stamp = source_stamp;
            this.keypoints = keypoints;
        }

        public static JointKeypointsMsg Deserialize(MessageDeserializer deserializer) => new JointKeypointsMsg(deserializer);

        private JointKeypointsMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.source_stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.keypoints, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.source_stamp);
            serializer.WriteLength(this.keypoints);
            serializer.Write(this.keypoints);
        }

        public override string ToString()
        {
            return "JointKeypointsMsg: " +
            "\nheader: " + header.ToString() +
            "\nsource_stamp: " + source_stamp.ToString() +
            "\nkeypoints: " + System.String.Join(", ", keypoints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
