//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class SpatialMeshMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/SpatialMesh";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Message for transporting spatial mapping mesh updates received from
        //  the HoloLens.
        // 
        public string mesh_id;
        //  Signals if this mesh should be removed from the world map
        public bool removal;
        public Shape.MeshMsg mesh;

        public SpatialMeshMsg()
        {
            this.mesh_id = "";
            this.removal = false;
            this.mesh = new Shape.MeshMsg();
        }

        public SpatialMeshMsg(string mesh_id, bool removal, Shape.MeshMsg mesh)
        {
            this.mesh_id = mesh_id;
            this.removal = removal;
            this.mesh = mesh;
        }

        public static SpatialMeshMsg Deserialize(MessageDeserializer deserializer) => new SpatialMeshMsg(deserializer);

        private SpatialMeshMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mesh_id);
            deserializer.Read(out this.removal);
            this.mesh = Shape.MeshMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mesh_id);
            serializer.Write(this.removal);
            serializer.Write(this.mesh);
        }

        public override string ToString()
        {
            return "SpatialMeshMsg: " +
            "\nmesh_id: " + mesh_id.ToString() +
            "\nremoval: " + removal.ToString() +
            "\nmesh: " + mesh.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
