//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class SystemTextResponseMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/SystemTextResponse";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Message indicating a generated textual answer for a provided query 
        //  utterance received from a user.
        // 
        //  The header primarily encapsulates when this message was emitted.
        //  The time component of this may be utilized as an identifier for this user
        //  intent and utterance.
        public Std.HeaderMsg header;
        //  User utterance received as input to a ROS node.
        public string utterance_text;
        //  Generated system response text for received user utterance input.
        public string response;

        public SystemTextResponseMsg()
        {
            this.header = new Std.HeaderMsg();
            this.utterance_text = "";
            this.response = "";
        }

        public SystemTextResponseMsg(Std.HeaderMsg header, string utterance_text, string response)
        {
            this.header = header;
            this.utterance_text = utterance_text;
            this.response = response;
        }

        public static SystemTextResponseMsg Deserialize(MessageDeserializer deserializer) => new SystemTextResponseMsg(deserializer);

        private SystemTextResponseMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.utterance_text);
            deserializer.Read(out this.response);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.utterance_text);
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "SystemTextResponseMsg: " +
            "\nheader: " + header.ToString() +
            "\nutterance_text: " + utterance_text.ToString() +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
