//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class SystemCommandsMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/SystemCommands";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Fields that may be interpreted by various system components as commands to be
        //  followed.
        // 
        //  Each command must have some sort of defined "default" state which is
        //  interpreted as "no command issued" so that a consumer may understand whether
        //  a command needs to be enacted on or has just not been requested via the
        //  received message instance.
        // 
        //  Task Monitor commands
        public bool reset_current_task;
        public bool previous_step;
        public bool next_step;

        public SystemCommandsMsg()
        {
            this.reset_current_task = false;
            this.previous_step = false;
            this.next_step = false;
        }

        public SystemCommandsMsg(bool reset_current_task, bool previous_step, bool next_step)
        {
            this.reset_current_task = reset_current_task;
            this.previous_step = previous_step;
            this.next_step = next_step;
        }

        public static SystemCommandsMsg Deserialize(MessageDeserializer deserializer) => new SystemCommandsMsg(deserializer);

        private SystemCommandsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.reset_current_task);
            deserializer.Read(out this.previous_step);
            deserializer.Read(out this.next_step);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.reset_current_task);
            serializer.Write(this.previous_step);
            serializer.Write(this.next_step);
        }

        public override string ToString()
        {
            return "SystemCommandsMsg: " +
            "\nreset_current_task: " + reset_current_task.ToString() +
            "\nprevious_step: " + previous_step.ToString() +
            "\nnext_step: " + next_step.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
