//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class TaskGraphMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/TaskGraph";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Message exporting the task (directed) graph structure.
        // 
        //  TODO: format likely depends on decisions regarding programatic structure, e.g.
        //        there are parallel threads looking into PDDL loading / representation,
        //        etc.
        // 
        public string[] task_steps;
        public uint[] task_levels;

        public TaskGraphMsg()
        {
            this.task_steps = new string[0];
            this.task_levels = new uint[0];
        }

        public TaskGraphMsg(string[] task_steps, uint[] task_levels)
        {
            this.task_steps = task_steps;
            this.task_levels = task_levels;
        }

        public static TaskGraphMsg Deserialize(MessageDeserializer deserializer) => new TaskGraphMsg(deserializer);

        private TaskGraphMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_steps, deserializer.ReadLength());
            deserializer.Read(out this.task_levels, sizeof(uint), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.task_steps);
            serializer.Write(this.task_steps);
            serializer.WriteLength(this.task_levels);
            serializer.Write(this.task_levels);
        }

        public override string ToString()
        {
            return "TaskGraphMsg: " +
            "\ntask_steps: " + System.String.Join(", ", task_steps.ToList()) +
            "\ntask_levels: " + System.String.Join(", ", task_levels.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
