//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class UtteranceMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/Utterance";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Represents an utterance from ASR.
        // 
        public string speaker;
        public string value;

        public UtteranceMsg()
        {
            this.speaker = "";
            this.value = "";
        }

        public UtteranceMsg(string speaker, string value)
        {
            this.speaker = speaker;
            this.value = value;
        }

        public static UtteranceMsg Deserialize(MessageDeserializer deserializer) => new UtteranceMsg(deserializer);

        private UtteranceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.speaker);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.speaker);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "UtteranceMsg: " +
            "\nspeaker: " + speaker.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
