//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Angel
{
    [Serializable]
    public class VisionBoundingBox3dMsg : Message
    {
        public const string k_RosMessageName = "angel_msgs/VisionBoundingBox3d";
        public override string RosMessageName => k_RosMessageName;

        //  NOTE: This is the same BoundingBox3d message that is in vision_msgs. It is 
        //  copied here because the ROS-TCP-Connector package does not have vision_msgs
        //  included.
        //  A 3D bounding box that can be positioned and rotated about its center (6 DOF)
        //  Dimensions of this box are in meters, and as such, it may be migrated to
        //    another package, such as geometry_msgs, in the future.
        //  The 3D position and orientation of the bounding box center
        public Geometry.PoseMsg center;
        //  The size of the bounding box, in meters, surrounding the object's center
        //    pose.
        public Geometry.Vector3Msg size;

        public VisionBoundingBox3dMsg()
        {
            this.center = new Geometry.PoseMsg();
            this.size = new Geometry.Vector3Msg();
        }

        public VisionBoundingBox3dMsg(Geometry.PoseMsg center, Geometry.Vector3Msg size)
        {
            this.center = center;
            this.size = size;
        }

        public static VisionBoundingBox3dMsg Deserialize(MessageDeserializer deserializer) => new VisionBoundingBox3dMsg(deserializer);

        private VisionBoundingBox3dMsg(MessageDeserializer deserializer)
        {
            this.center = Geometry.PoseMsg.Deserialize(deserializer);
            this.size = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.center);
            serializer.Write(this.size);
        }

        public override string ToString()
        {
            return "VisionBoundingBox3dMsg: " +
            "\ncenter: " + center.ToString() +
            "\nsize: " + size.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
