_BASE_: "/home/local/KHQ/hannah.defazio/angel_system/angel_system/berkeley/configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 5
    SCORE_THRESH_TEST: 0.0001
    NAME: StandardROIHeads_PLUS_CONTACT
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("BBN_M2_YoloModel_train",)
  TEST: ("BBN_M2_YoloModel_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
  FILTER_EMPTY_ANNOTATIONS: True

OUTPUT_DIR: '/data/ptg/medical/training/bbn_M2/yolomodel_data/resnet101'

SOLVER:
  TOTAL_IMAGE_NUMBER: 6064
  IMS_PER_BATCH: 21
  BASE_LR: 0.001
  STEPS: (34000, 41000)
# MAX_ITER: 64000 # 500 * 1 / 10 ~ 500 epochs
  CHECKPOINT_PERIOD: 1000
  EPOCH: 50

VISUALIZER:
  CAM: False


