# Get all of the task graphs for the current tasks.

# This field is required b/c the ROS TCP bridge cannot handle deserializing an
# empty request
uint8 test
---
# Response
# List of task titles to monitor
string[] task_titles

# List of TaskGraphs - must be equal in length to `task_titles`
angel_msgs/TaskGraph[] task_graphs
